import { useNavigate } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'

const SECTIONS = [
  {
    title: '1. Who we are',
    body: `NeuroPhysics is an educational app designed to help GCSE students — particularly neurodivergent learners — revise Physics. The app is operated by the developer ("we", "us", "our").`,
  },
  {
    title: '2. What data we collect',
    body: `We collect as little data as possible:\n\n• Learning progress (topics started, mastered, XP, streak) — stored locally on your device only.\n• Accessibility preferences (reduce motion, high contrast, font settings) — stored locally on your device only.\n• Chat messages sent to the Mamo AI tutor — transmitted to Anthropic's API to generate a response, then discarded. We do not store your chat history.\n\nWe do not collect your name, email address, location, or any other personal information.`,
  },
  {
    title: '3. AI-generated content',
    body: `The Mamo chat feature uses Claude, an AI model made by Anthropic (anthropic.com). Messages you send are processed by Anthropic's servers to generate responses. Anthropic's Privacy Policy applies to this processing: https://www.anthropic.com/privacy\n\nAll Mamo responses are generated by AI and should not be treated as a substitute for teacher advice.`,
  },
  {
    title: '4. How we store data',
    body: `All progress and preference data is stored locally on your device using standard iOS storage. It is not uploaded to any server or shared with any third party. Clearing the app's data or deleting the app removes all stored data permanently.`,
  },
  {
    title: '5. Children\'s privacy',
    body: `NeuroPhysics is intended for users aged 13 and over. We do not knowingly collect personal information from children under 13. If you are under 13, please do not use this app without parental consent.\n\nParents or guardians who believe their child under 13 has used the app may contact us to request data deletion.`,
  },
  {
    title: '6. Your rights',
    body: `You can delete all locally stored data at any time by going to Settings → Clear All My Data within the app, or by deleting the app from your device.\n\nFor any questions about your data, contact us at the support address below.`,
  },
  {
    title: '7. Third-party services',
    body: `We use the following third-party services:\n\n• Anthropic Claude API — powers the Mamo AI tutor. Messages are sent to Anthropic's servers. See anthropic.com/privacy.\n• Vercel — hosts the API proxy. Vercel may log request metadata (IP address, timestamps). See vercel.com/legal/privacy-policy.`,
  },
  {
    title: '8. Changes to this policy',
    body: `We may update this Privacy Policy from time to time. The latest version will always be available within the app under Settings → Privacy Policy. Continued use of the app after changes constitutes acceptance of the updated policy.`,
  },
  {
    title: '9. Contact',
    body: `For privacy-related questions or data deletion requests, please contact:\nsupport@neurophysics.app`,
  },
]

export default function PrivacyPolicyScreen() {
  const navigate = useNavigate()

  return (
    <div className="flex flex-col h-full overflow-hidden" style={{ background: '#0b1121' }}>
      {/* Header */}
      <div className="px-5 pt-5 pb-4 shrink-0 flex items-center gap-3" style={{ borderBottom: '0.75px solid #1d293d' }}>
        <button
          onClick={() => navigate(-1)}
          className="w-11 h-11 rounded-[12px] flex items-center justify-center shrink-0"
          style={{ background: 'rgba(18,26,47,0.9)', border: '0.75px solid #1d293d' }}
          aria-label="Go back"
        >
          <ArrowLeft size={18} color="#a8b8cc" />
        </button>
        <h1 className="text-base font-bold" style={{ color: '#f8fafc' }}>Privacy Policy</h1>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto px-5 py-5 space-y-6">
        <p className="text-xs" style={{ color: '#a8b8cc' }}>Last updated: April 2026</p>

        {SECTIONS.map(s => (
          <div key={s.title}>
            <h2 className="text-sm font-bold mb-2" style={{ color: '#f8fafc' }}>{s.title}</h2>
            <p className="text-sm leading-relaxed whitespace-pre-line break-words" style={{ color: '#a8b8cc' }}>{s.body}</p>
          </div>
        ))}

        <div style={{ height: 32 }} />
      </div>
    </div>
  )
}
